using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace OrderManagementApi.Models
{
    public class Order
    {
        // Auto-generated by the backend
        [Key]  // Marks this property as the primary key
        [JsonIgnore]
        public int OrderId { get; set; }

        [Required]
        public DateTime OrderDate { get; set; }

        // Computed by the backend
        [JsonIgnore]
        public decimal TotalAmount { get; set; }

        [Required]
        public List<OrderItem>? OrderItems { get; set; }
    }
}
